version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - 8090:8090
    environment:
      - NODE_ENV=prod
      - DB_HOST=db
      - DATABASE_URI=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      - REDIS_URL=redis://default:redis@redis:6379

  redis:
    image: redis:6.0.6-alpine3.12
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass redis

volumes:
  db:
