name: CI-integration-tests

on:
  push:
    branches: [master, feature, dev, hotfix-**]
  pull_request:
    branches: [master, feature, dev]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    container: node:16

    services:
      mariadb:
        ports:
          - 3306:3306
        image: mariadb

        env:
          MYSQL_DATABASE: twitch
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci
          npm install typescript
          npm run build
      - name: Run integrations tests
        run: npm run integration-tests

        env:
          DB_HOST: mariadb
          DB_PORT: 3306
          DB_USERNAME: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_DATABASE: twitch
