name: CI-build

on:
  push:
    branches: [master, feature, dev, hotfix-**]
  pull_request:
    branches: [master, feature, dev]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run build and lint script
        run: |
          npm run lint
