name: Integration tests
on: push
jobs:
  
  container-job:
    
    runs-on: ubuntu-latest
    
    container: node:16
    
    services:
      
      mariadb:
        ports:
          - 3306:3306
        image: mariadb
        
        env:
          MYSQL_DATABASE: twitch
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v3
      
      
      - name: Install dependencies
        run: |
          npm ci
          npm install typescript
          npm run build
      - name: Run Tests
        run: npm t
        
        env:
          DB_HOST: mariadb
          DB_PORT: 3306
          DB_USERNAME: admin
          DB_PASSWORD: test
          DB_DATABASE: twitch